### PR TITLE
[bug]start up mulit redis server

### PR DESCRIPTION
**Pull request by zhenchuan**
related to issue #5

### CODE REVIEW

**Comment by graemerocher** [comment]
@zhenchuan Could you sign the CLA for this one?

**Comment by zhenchuan** [comment]
> @zhenchuan Could you sign the CLA for this one?

👌，i have signed the CLA

**Comment by graemerocher** [comment]
Seems you did the commits with a different account. That account also needs to sign. Thanks

**Comment by zhenchuan** [comment]
> Seems you did the commits with a different account. That account also needs to sign. Thanks

sorry, re-signed again.

**Comment by jzemke** [comment]
@zhenchuan looks like the Travis CI build failed due to missing javadocs? am interested in getting this merged, currently experiencing the same issue.

**Pull request merged**
