### PR TITLE
Refactor RedisCache to use commands directly

### PR DESCRIPTION
**Pull request by dstepanov**
- That removes usage of a proxy
- Async calls are now chained, should be more correct and readable

### CODE REVIEW

**Comment by graemerocher** [comment]
Client code may be depending on these deleted interfaces

**Comment by dstepanov** [comment]
Also refactored Redis Session

**Comment by dstepanov** [comment]
Fixes #1 #30 and maybe #38

**Comment by ktholen** [comment]
Just ran into this issue today, pulled the branch down and it looks like it works! Looking forward to seeing this merged and released!

Thanks @dstepanov

**Comment by ktholen** [comment]
@graemerocher any chance we could get this released?

**Comment by graemerocher** [comment]
Thanks!

**Pull request merged**
