### PR TITLE
Support dynamic TTLs based on an object

### PR DESCRIPTION
**Pull request by ktholen**
We have a need to be able to change the TTL based on an object. This change will allow us to configure the TTLs dynamically.

### CODE REVIEW

**Comment by ktholen** [comment]
@sdelamo -> Its not quite clear on what the process is to have PRs merged. Let me know if you have any feedback/questions.

Thank you,

Kevin

**Comment by jameskleeh** [comment]
Instead of configuring a class name and then expecting it to be a bean, the configuration class can simply attempt to inject an instance of `ExpirationAfterWritePolicy` and if it is null, return a new instance of `ConstantExpirationAfterWritePolicy`. Also please remove any whitespace only changes

**Comment by graemerocher** [comment]
Also please fix the merge conflicts after merging the other PR

**Comment by ktholen** [comment]
I'll make the updates to the formatting and conflicts.

@jameskleeh in regards to the configuration, I was using a path because the RedisConfiguration is defined per cache-name and not globally. So I was thinking there could be several of these configurations. If you still prefer to only support one configuration that is fine, we can work around that on our end.

**Comment by ktholen** [comment]
@jameskleeh -> All changes have been made, as I mentioned above I think the configuration should stay per cache level. If you disagree let me know so I can make the changes today.

**Comment by jameskleeh** [comment]
@ktholen OK with me. I think the only thing missing is documentation

**Comment by jameskleeh** [comment]
Also need to test the misconfigured cases to ensure it fails expectedly

1. Bean not present
2. Class not found
3. Bean not of required type

**Comment by ktholen** [comment]
@jameskleeh -> I have added the three tests and added a configuration sample to the docs. Let me know if you see anything else!

**Comment by graemerocher** [comment]
Thanks for the contribution

**Pull request merged**
