### PR TITLE
ci: build to 6.0.1, test to 4.0.0-SNAPSHOT, groovy to 4.0.6, spock to 2.3-groovy-4.0, github workflows to Java 17

### PR DESCRIPTION
**Pull request by wetted**

### CODE REVIEW

**Comment by wetted** [comment]
ping @timyates

This has issues with `caffeine`. For example, `ExpirationSpec` failed with the following, and is a consequence if the removal of shaded `caffeine` from core. 

```
Error instantiating bean of type  [io.micronaut.cache.interceptor.CacheInterceptor]

Message: io/micronaut/caffeine/cache/Cache
Path Taken: new $TimeService$Definition$Intercepted(BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors) --> new $TimeService$Definition$Intercepted(BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,[List $interceptors]) --> new CacheInterceptor([CacheManager cacheManager],CacheErrorHandler errorHandler,AsyncCacheErrorHandler asyncCacheErrorHandler,ExecutorService ioExecutor,BeanContext beanContext)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.cache.interceptor.CacheInterceptor]
```

**Comment by timyates** [comment]
Yes, `io/micronaut/caffeine/cache/Cache` doesn't exist any more, you need the class in com.benmanes.caffeine...

**Comment by wetted** [comment]
> Yes, `io/micronaut/caffeine/cache/Cache` doesn't exist any more, you need the class in com.benmanes.caffeine...

Right, that I knew, but I think this is a runtime dependency from another module. I’ll look into it tomorrow to see where it’s coming from. I would have gotten a compile error if was directly in `micronaut-redis`.

**Comment by timyates** [comment]
Yeah, I believe the issue is micronaut-micrometer has 

```
        if (nativeCache instanceof io.micronaut.caffeine.cache.Cache) {
```

On line 62

We probably need a v 5.0.0-SNAPSHOT of that first

**Comment by wetted** [comment]
Yeah, I also need to first update that branch of `micronaut-micrometer` for the changes to core and build plugins, so I will do that first.

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
