### PR TITLE
Support custom RedisCodec Bean injection in the auto-configuration

### PR DESCRIPTION
**Pull request by jfsanchez91**

### CODE REVIEW

**Comment by jfsanchez91** [comment]
WIP to provide a solution for https://github.com/micronaut-projects/micronaut-redis/issues/341

**Comment by sdelamo** [comment]
@timyates can you check this PR and give @jfsanchez91 feedback?

**Comment by timyates** [comment]
@jfsanchez91 Hiya! Thanks for this contribution!

As it's a breaking change to the public API, it will be good to get in to Micronaut 4.0.0 and Redis 6.0.0

1. There's some checkstyle failures around javadoc
2. This PR changes the codec globally, but is there a way we could [also support named servers](https://micronaut-projects.github.io/micronaut-redis/latest/guide/configurationreference.html#io.micronaut.configuration.lettuce.NamedRedisServersConfiguration)?

**Comment by jfsanchez91** [comment]
Hi sorry for the delay. I have been busy with my new consulting project :).
I will try to finish this :).
Thx for the feedback @sdelamo & @timyates

**Comment by jfsanchez91** [comment]
@timyates what is exactly needed to be supported in the named servers?
I already introduced the generic codec support in [NamedRedisClientFactory](https://github.com/micronaut-projects/micronaut-redis/pull/342/files#diff-44b067641e9640d26e326ed0b1b83722d713fd9fecf8bdff11e80d1a335baf74R43).  
Is there anything else to be changed?

**Comment by timyates** [comment]
@jfsanchez91 I'll have a think how we can do this...

The issue is that we allow configuring [multiple redis servers](https://micronaut-projects.github.io/micronaut-redis/latest/guide/#_multiple_redis_connections), and I guess we need to consider how we can set the Codec on a per-server basis 🤔

**Comment by timyates** [comment]
@jfsanchez91 I *think* this does what we want https://github.com/micronaut-projects/micronaut-redis/pull/348 🤞 

I'll close this for now, as your work is in that new PR 👍 

Thanks again for the contribution!

**Pull request closed without merging**
